import { createDefaultTripChecklistItems } from "./checklist";
import type { Trip } from "./types";

// 公开示例只展示可编辑行程，不预填供应商媒体、身份标识或服务查询快照。
export const seedTrips: Trip[] = [
  {
    id: "seed-xian",
    title: "西安 3 日历史文化行",
    destination: "西安",
    currency: "CNY",
    startDate: "2026-06-12",
    endDate: "2026-06-14",
    status: "计划中",
    createdAt: "2026-05-04T00:00:00.000Z",
    updatedAt: "2026-05-04T00:00:00.000Z",
    importSources: [
      {
        id: "seed-xian-source-1",
        title: "西安三日历史文化路线",
        sourceType: "link",
        status: "已导入",
      },
      {
        id: "seed-xian-source-2",
        title: "钟楼和兵马俑周边备选清单",
        sourceType: "text",
        status: "待解析",
      },
    ],
    checklistItems: createDefaultTripChecklistItems(),
    budget: {
      amount: 2600,
      currency: "CNY",
    },
    expenses: [
      {
        id: "seed-xian-expense-1",
        title: "往返交通预估",
        amount: 680,
        category: "交通",
        currency: "CNY",
        date: "2026-06-12",
        note: "高铁和市内交通预留",
        createdAt: "2026-05-04T08:10:00.000Z",
        updatedAt: "2026-05-04T08:10:00.000Z",
      },
      {
        id: "seed-xian-expense-2",
        title: "钟楼附近酒店",
        amount: 720,
        category: "住宿",
        currency: "CNY",
        date: "2026-06-12",
        note: "两晚住宿预估",
        createdAt: "2026-05-04T08:12:00.000Z",
        updatedAt: "2026-05-04T08:12:00.000Z",
      },
    ],
    transports: [
      {
        id: "seed-xian-transport-1",
        type: "火车",
        title: "抵达西安北站",
        detail: "到站后乘地铁 2 号线进城，先去酒店放行李",
        arrivalTime: "06 月 12 日 09:30",
      },
      {
        id: "seed-xian-transport-2",
        type: "巴士",
        title: "前往临潼兵马俑",
        detail: "从市区出发预留 1.5 小时，回程避开晚高峰",
        departureTime: "06 月 14 日 08:30",
      },
    ],
    lodgings: [
      {
        id: "seed-xian-lodging-1",
        name: "钟楼附近酒店",
        address: "西安市碑林区钟楼商圈周边",
        checkIn: "06 月 12 日",
        checkOut: "06 月 14 日",
        note: "靠近地铁 2 号线，方便去大雁塔、钟楼和西安北站",
      },
    ],
    memos: [
      {
        id: "seed-xian-memo-1",
        title: "预约提醒",
        detail: "陕西历史博物馆和兵马俑门票提前预约",
        pinned: true,
      },
      {
        id: "seed-xian-memo-2",
        title: "天气提醒",
        detail: "白天注意防晒，晚上逛不夜城和城墙可带薄外套",
        pinned: true,
      },
    ],
    places: [
      {
        id: "seed-xian-place-1",
        name: "大雁塔",
        category: "景点",
        isScheduled: true,
        area: "雁塔区",
        address: "慈恩路1号大慈恩寺内",
        iconKey: "landmark",
        osmKey: "historic",
        osmValue: "monument",
        poiGroup: "attraction",
        poiType: "pagoda",
        provider: "mock",
        photos: [],
        details: {
          summary:
            "演示行程地点，可按自己的旅行计划编辑；营业信息请以实际查询为准。",
        },
        externalImages: [],
      },
      {
        id: "seed-xian-place-2",
        name: "陕西历史博物馆",
        category: "景点",
        isScheduled: true,
        area: "雁塔区",
        address: "小寨东路91号",
        iconKey: "museum",
        osmKey: "tourism",
        osmValue: "museum",
        poiGroup: "attraction",
        poiType: "museum",
        provider: "mock",
        photos: [],
        details: {
          summary:
            "演示行程地点，可按自己的旅行计划编辑；营业信息请以实际查询为准。",
        },
        externalImages: [],
      },
      {
        id: "seed-xian-place-3",
        name: "大唐不夜城",
        category: "景点",
        isScheduled: true,
        area: "雁塔区",
        address: "雁塔南路428号",
        iconKey: "attraction",
        osmKey: "tourism",
        osmValue: "attraction",
        poiGroup: "attraction",
        poiType: "pedestrian_street",
        provider: "mock",
        photos: [],
        details: {
          summary:
            "演示行程地点，可按自己的旅行计划编辑；营业信息请以实际查询为准。",
        },
        externalImages: [],
      },
      {
        id: "seed-xian-place-4",
        name: "钟楼",
        category: "景点",
        isScheduled: true,
        area: "莲湖区",
        address: "西安地铁2号线钟楼站C出口正对面",
        iconKey: "landmark",
        osmKey: "historic",
        osmValue: "monument",
        poiGroup: "attraction",
        poiType: "bell_tower",
        provider: "mock",
        photos: [],
        details: {
          summary:
            "演示行程地点，可按自己的旅行计划编辑；营业信息请以实际查询为准。",
        },
        externalImages: [],
      },
      {
        id: "seed-xian-place-5",
        name: "鼓楼",
        category: "景点",
        isScheduled: true,
        area: "莲湖区",
        address: "北院门74号(广济街地铁站D1口步行370米)",
        iconKey: "landmark",
        osmKey: "historic",
        osmValue: "monument",
        poiGroup: "attraction",
        poiType: "drum_tower",
        provider: "mock",
        photos: [],
        details: {
          summary:
            "演示行程地点，可按自己的旅行计划编辑；营业信息请以实际查询为准。",
        },
        externalImages: [],
      },
      {
        id: "seed-xian-place-6",
        name: "回民街",
        category: "餐厅",
        isScheduled: true,
        area: "莲湖区",
        address: "北院门125号1-51(钟楼地铁站出入口步行430米)",
        iconKey: "restaurant",
        osmKey: "amenity",
        osmValue: "restaurant",
        poiGroup: "food",
        poiType: "food_street",
        provider: "mock",
        photos: [],
        details: {
          summary:
            "演示行程地点，可按自己的旅行计划编辑；营业信息请以实际查询为准。",
        },
        externalImages: [],
      },
      {
        id: "seed-xian-place-7",
        name: "西安城墙永宁门",
        category: "景点",
        isScheduled: true,
        area: "碑林区",
        address: "南大街2号西安城墙内(南侧)",
        iconKey: "landmark",
        osmKey: "historic",
        osmValue: "citywalls",
        poiGroup: "attraction",
        poiType: "city_wall",
        provider: "mock",
        photos: [],
        details: {
          summary:
            "演示行程地点，可按自己的旅行计划编辑；营业信息请以实际查询为准。",
        },
        externalImages: [],
      },
      {
        id: "seed-xian-place-8",
        name: "秦始皇帝陵博物院(兵马俑)",
        category: "景点",
        isScheduled: true,
        area: "临潼区",
        address: "秦陵北路",
        iconKey: "museum",
        osmKey: "tourism",
        osmValue: "museum",
        poiGroup: "attraction",
        poiType: "museum",
        provider: "mock",
        photos: [],
        details: {
          summary:
            "演示行程地点，可按自己的旅行计划编辑；营业信息请以实际查询为准。",
        },
        externalImages: [],
      },
      {
        id: "seed-xian-place-9",
        name: "华清宫",
        category: "景点",
        isScheduled: true,
        area: "临潼区",
        address: "华清路38号",
        iconKey: "temple",
        osmKey: "tourism",
        osmValue: "attraction",
        poiGroup: "attraction",
        poiType: "palace",
        provider: "mock",
        photos: [],
        details: {
          summary:
            "演示行程地点，可按自己的旅行计划编辑；营业信息请以实际查询为准。",
        },
        externalImages: [],
      },
      {
        id: "seed-xian-place-10",
        name: "骊山",
        category: "景点",
        isScheduled: true,
        area: "临潼区",
        address: "临潼区",
        iconKey: "viewpoint",
        osmKey: "natural",
        osmValue: "peak",
        poiGroup: "attraction",
        poiType: "mountain",
        provider: "mock",
        photos: [],
        details: {
          summary:
            "演示行程地点，可按自己的旅行计划编辑；营业信息请以实际查询为准。",
        },
        externalImages: [],
      },
    ],
    days: [
      {
        id: "seed-xian-day-1",
        dayIndex: 1,
        title: "第一天 · 大唐不夜城附近",
        summary:
          "围绕大雁塔、大悦城和大唐不夜城一带安排，白天看展，晚上步行逛夜景。",
        items: [
          {
            id: "seed-xian-item-1",
            time: "10:30",
            title: "陕西历史博物馆",
            category: "景点",
            iconKey: "museum",
            placeId: "seed-xian-place-2",
            placeName: "陕西历史博物馆",
            note: "提前预约，按展厅重点看周秦汉唐部分",
            cost: 0,
            costRecordedAt: "2026-06-12T10:30:00.000Z",
          },
          {
            id: "seed-xian-item-2",
            time: "14:30",
            title: "大雁塔",
            category: "景点",
            iconKey: "landmark",
            placeId: "seed-xian-place-1",
            placeName: "大雁塔",
            note: "从南北广场和大慈恩寺周边慢走",
          },
          {
            id: "seed-xian-item-3",
            time: "19:30",
            title: "大唐不夜城",
            category: "景点",
            iconKey: "attraction",
            placeId: "seed-xian-place-3",
            placeName: "大唐不夜城",
            note: "晚上看灯光和街区表演，注意人流",
          },
        ],
      },
      {
        id: "seed-xian-day-2",
        dayIndex: 2,
        title: "第二天 · 钟楼附近",
        summary: "以钟楼为中心，把鼓楼、回民街和城墙南门串成一条市中心步行线。",
        items: [
          {
            id: "seed-xian-item-4",
            time: "09:30",
            title: "钟楼",
            category: "景点",
            iconKey: "landmark",
            placeId: "seed-xian-place-4",
            placeName: "钟楼",
            note: "从地下通道进出更方便，顺手确认晚上拍照角度",
          },
          {
            id: "seed-xian-item-5",
            time: "11:00",
            title: "鼓楼",
            category: "景点",
            iconKey: "landmark",
            placeId: "seed-xian-place-5",
            placeName: "鼓楼",
            note: "和钟楼可联票，也可以只在广场周边逛",
          },
          {
            id: "seed-xian-item-6",
            time: "12:30",
            title: "回民街",
            category: "餐厅",
            iconKey: "restaurant",
            placeId: "seed-xian-place-6",
            placeName: "回民街",
            note: "午餐放轻松，留一点胃给晚上的小吃",
            cost: 80,
            costRecordedAt: "2026-06-13T12:30:00.000Z",
          },
          {
            id: "seed-xian-item-7",
            time: "16:30",
            title: "西安城墙永宁门",
            category: "景点",
            iconKey: "landmark",
            placeId: "seed-xian-place-7",
            placeName: "西安城墙永宁门",
            note: "傍晚上城墙，天气合适可以租车骑一段",
            cost: 54,
            costRecordedAt: "2026-06-13T16:30:00.000Z",
          },
        ],
      },
      {
        id: "seed-xian-day-3",
        dayIndex: 3,
        title: "第三天 · 兵马俑附近",
        summary: "临潼一日，把兵马俑作为主线，顺路安排华清宫和骊山。",
        items: [
          {
            id: "seed-xian-item-8",
            time: "10:00",
            title: "秦始皇帝陵博物院(兵马俑)",
            category: "景点",
            iconKey: "museum",
            placeId: "seed-xian-place-8",
            placeName: "秦始皇帝陵博物院(兵马俑)",
            note: "建议请讲解或租讲解器，先看一号坑",
            cost: 120,
            costRecordedAt: "2026-06-14T10:00:00.000Z",
          },
          {
            id: "seed-xian-item-9",
            time: "14:30",
            title: "华清宫",
            category: "景点",
            iconKey: "temple",
            placeId: "seed-xian-place-9",
            placeName: "华清宫",
            note: "看唐代遗址和温泉文化，和骊山动线合并",
            cost: 120,
            costRecordedAt: "2026-06-14T14:30:00.000Z",
          },
          {
            id: "seed-xian-item-10",
            time: "16:30",
            title: "骊山",
            category: "景点",
            iconKey: "viewpoint",
            placeId: "seed-xian-place-10",
            placeName: "骊山",
            note: "体力一般就只走近处观景点，给回城留时间",
          },
        ],
      },
    ],
  },
];
