import { Dimensions, StyleSheet } from "react-native";

import type { AppTheme } from "@/shared/theme/theme";

export const SCREEN_WIDTH = Dimensions.get("window").width;
export const PLACE_DETAIL_MAX_WIDTH = 620;
export const PLACE_DETAIL_HORIZONTAL_PADDING = 20;
export const PLACE_DASHBOARD_GRID_GAP = 12;
export const PLACE_DASHBOARD_BASE_CARD_SIZE = 232;
export const PLACE_WEATHER_BASE_CARD_SIZE = 201;
export const PLACE_WEATHER_MIN_CONTENT_SCALE = 0.8;
export const PLACE_WEATHER_MAX_CONTENT_SCALE = 1.15;
export const PLACE_BOTTOM_ACTION_BAR_MAX_WIDTH = 480;
export const PLACE_BOTTOM_ACTION_BAR_WIDTH_RATIO = 0.85;
export const PLACE_MORE_MENU_WIDTH = 224;

export function getPlaceDashboardCardSize(viewportWidth: number): number {
  const contentWidth = Math.min(viewportWidth, PLACE_DETAIL_MAX_WIDTH);
  const availableWidth = Math.max(
    0,
    contentWidth -
      PLACE_DETAIL_HORIZONTAL_PADDING * 2 -
      PLACE_DASHBOARD_GRID_GAP,
  );

  return Math.max(158, availableWidth / 2);
}

export function getPlaceWeatherContentScale(cardSize: number): number {
  return Math.min(
    PLACE_WEATHER_MAX_CONTENT_SCALE,
    Math.max(
      PLACE_WEATHER_MIN_CONTENT_SCALE,
      cardSize / PLACE_WEATHER_BASE_CARD_SIZE,
    ),
  );
}
export function createPlaceDetailStyles(
  theme: AppTheme,
  dashboardCardSize: number,
) {
  const dashboardScale = Math.min(
    1,
    dashboardCardSize / PLACE_DASHBOARD_BASE_CARD_SIZE,
  );
  const weatherContentScale = getPlaceWeatherContentScale(dashboardCardSize);
  const scaleDashboard = (value: number) => value * dashboardScale;
  const scaleWeather = (value: number) => value * weatherContentScale;

  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.colors.surfaceMuted,
    },
    content: {
      alignSelf: "center",
      width: "100%",
      maxWidth: PLACE_DETAIL_MAX_WIDTH,
      paddingHorizontal: PLACE_DETAIL_HORIZONTAL_PADDING,
      paddingTop: 12,
      paddingBottom: 112,
      gap: 14,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    iconButton: {
      alignItems: "center",
      justifyContent: "center",
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: theme.colors.surface,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 3,
      elevation: 2,
    },
    iconButtonPressed: {
      backgroundColor: theme.colors.surfaceMuted,
    },
    subtitle: {
      color: theme.colors.textMuted,
      fontSize: 13,
      lineHeight: 19,
    },
    card: {
      gap: 10,
      padding: 16,
      borderRadius: 16,
      backgroundColor: theme.colors.surface,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    loadingCard: {
      minHeight: 112,
      alignItems: "center",
      justifyContent: "center",
    },
    heroPanel: {
      overflow: "hidden",
      marginHorizontal: -20,
      borderRadius: 0,
      backgroundColor: theme.colors.surface,
    },
    heroMedia: {
      position: "relative",
      minHeight: 240,
      backgroundColor: theme.colors.surfaceSubtle,
    },
    heroImage: {
      width: "100%",
      height: 240,
    },
    heroPlaceholder: {
      minHeight: 240,
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      backgroundColor: theme.colors.surfaceMuted,
    },
    heroPlaceholderText: {
      color: theme.colors.textMuted,
      fontSize: 14,
      fontWeight: "700",
    },
    heroInfo: {
      paddingHorizontal: 16,
      paddingTop: 15,
      paddingBottom: 14,
    },
    heroTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
    },
    heroTitleCopy: {
      flex: 1,
      minWidth: 0,
      gap: 10,
    },
    heroCategoryIcon: {
      alignItems: "center",
      justifyContent: "center",
      width: 40,
      height: 40,
    },
    placeTitle: {
      color: theme.colors.text,
      fontSize: 24,
      fontWeight: "700",
      lineHeight: 30,
    },
    badgeRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      gap: 7,
    },
    badge: {
      minHeight: 28,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: theme.radius.pill,
      backgroundColor: theme.colors.primarySoft,
    },
    badgeText: {
      color: theme.colors.primary,
      fontSize: 11,
      fontWeight: "700",
      lineHeight: 14,
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    metricGrid: {
      flexDirection: "row",
      gap: 10,
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      marginTop: 16,
    },
    collapsibleSectionHeader: {
      minHeight: 36,
      paddingVertical: 4,
      paddingHorizontal: 2,
      borderRadius: 10,
    },
    collapsibleSectionHeaderPressed: {
      opacity: 0.6,
    },
    sectionHeaderAction: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 16,
      backgroundColor: theme.colors.surfaceMuted,
    },
    expenseSectionTitleBlock: {
      flex: 1,
      minWidth: 0,
      gap: 4,
    },
    expenseSectionTotal: {
      color: theme.colors.success,
      fontSize: 13,
      fontWeight: "600",
    },
    sectionTitle: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: "700",
      letterSpacing: -0.2,
    },
    sectionHint: {
      color: theme.colors.textSubtle,
      fontSize: 12,
      fontWeight: "500",
    },
    cardTitle: {
      color: theme.colors.text,
      fontSize: 20,
      fontWeight: "700",
    },
    itemTitle: {
      flexShrink: 1,
      color: theme.colors.text,
      fontSize: 15,
      fontWeight: "700",
    },
    mutedText: {
      color: theme.colors.textMuted,
      fontSize: 13,
      lineHeight: 19,
    },
    metaText: {
      color: theme.colors.slate,
      fontSize: 13,
      fontWeight: "500",
      lineHeight: 18,
    },
    costMetaText: {
      alignSelf: "flex-start",
      overflow: "hidden",
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 8,
      backgroundColor: theme.colors.successSoft,
      color: theme.colors.success,
      fontSize: 10,
      fontWeight: "600",
      lineHeight: 15,
    },
    expenseRecordRow: {
      minHeight: 52,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      paddingHorizontal: 10,
      paddingVertical: 10,
      borderRadius: 12,
      backgroundColor: theme.colors.surfaceMuted,
    },
    expenseRecordIcon: {
      alignItems: "center",
      justifyContent: "center",
      width: 32,
      height: 32,
      borderRadius: 10,
      backgroundColor: theme.colors.successSoft,
      shadowColor: theme.colors.success,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 2,
      elevation: 1,
    },
    expenseRecordCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    expenseRecordDate: {
      color: theme.colors.text,
      fontSize: 14,
      fontWeight: "600",
      lineHeight: 19,
    },
    expenseRecordTime: {
      color: theme.colors.textMuted,
      fontSize: 13,
      fontWeight: "500",
      lineHeight: 17,
    },
    expenseRecordAmount: {
      color: theme.colors.success,
      fontSize: 15,
      fontWeight: "700",
    },
    sectionTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    sourceBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 10,
      paddingVertical: 4,
      backgroundColor: theme.colors.surfaceMuted,
      borderRadius: 20,
    },
    sourceBadgeText: {
      color: theme.colors.slate,
      fontSize: 11,
      fontWeight: "600",
    },
    introQuoteRow: {
      flexDirection: "row",
      gap: 10,
    },
    introAccent: {
      width: 3,
      borderRadius: 2,
      backgroundColor: theme.colors.primary,
      opacity: 0.3,
    },
    introText: {
      flex: 1,
      color: theme.colors.slate,
      fontSize: 14,
      fontWeight: "500",
      lineHeight: 24,
      letterSpacing: 0.1,
    },
    introTextCollapsed: {
      overflow: "hidden",
    },
    sourceLinkRow: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "flex-end",
      gap: 4,
      marginTop: 4,
      paddingVertical: 4,
      paddingHorizontal: 2,
    },
    sourceLinkText: {
      color: theme.colors.primary,
      fontSize: 11,
      fontWeight: "700",
    },
    photoRail: {
      marginHorizontal: -16,
    },
    photoRailContent: {
      flexDirection: "row",
      gap: 8,
      paddingHorizontal: 16,
    },
    photoEmptyState: {
      minHeight: 82,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      padding: 12,
      borderRadius: 12,
      backgroundColor: theme.colors.surfaceMuted,
      borderWidth: 1,
      borderColor: theme.colors.borderStrong,
      borderStyle: "dashed",
    },
    photoEmptyIcon: {
      alignItems: "center",
      justifyContent: "center",
      width: 42,
      height: 42,
      borderRadius: 12,
      backgroundColor: theme.colors.surfaceSubtle,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.03,
      shadowRadius: 1,
      elevation: 1,
    },
    photoEmptyCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    photoSlot: {
      position: "relative",
      overflow: "hidden",
      width: 140,
      height: 180,
      borderRadius: 12,
      backgroundColor: theme.colors.surfaceMuted,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 2,
      elevation: 1,
    },
    photoSlotPressed: {
      opacity: 0.8,
    },
    photoSlotImage: {
      width: "100%",
      height: "100%",
    },
    photoSourceBadge: {
      position: "absolute",
      right: 6,
      bottom: 6,
      maxWidth: "86%",
      overflow: "hidden",
      paddingHorizontal: 7,
      paddingVertical: 3,
      borderRadius: 8,
      backgroundColor: "rgba(17, 24, 39, 0.72)",
      color: "#FFFFFF",
      fontSize: 10,
      fontWeight: "700",
    },
    detailRow: {
      minHeight: 48,
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
      paddingVertical: 6,
    },
    costCollapsedRow: {
      borderRadius: 12,
      paddingVertical: 4,
      paddingHorizontal: 2,
    },
    costCollapsedRowPressed: {
      opacity: 0.7,
    },
    placeNoteRow: {
      borderRadius: 12,
      paddingHorizontal: 2,
    },
    placeNoteRowPressed: {
      opacity: 0.7,
    },
    placeNoteEditorBlock: {
      paddingTop: 4,
      paddingBottom: 4,
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
    },
    detailIcon: {
      alignItems: "center",
      justifyContent: "center",
      width: 34,
      height: 34,
      borderRadius: 10,
      backgroundColor: theme.colors.primarySoft,
      marginTop: 2,
    },
    detailCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    detailLabel: {
      color: theme.colors.textMuted,
      fontSize: 12,
      fontWeight: "600",
    },
    detailValue: {
      color: theme.colors.text,
      fontSize: 13,
      fontWeight: "500",
      lineHeight: 19,
    },
    recordMetric: {
      minHeight: 82,
      flex: 1,
      minWidth: 0,
      alignItems: "center",
      justifyContent: "center",
      gap: 4,
      padding: 10,
      borderRadius: 12,
      backgroundColor: theme.colors.surfaceMuted,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    recordMetricIcon: {
      alignItems: "center",
      justifyContent: "center",
      width: 28,
      height: 28,
      borderRadius: 10,
      backgroundColor: theme.colors.primarySoft,
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 2,
      elevation: 1,
    },
    recordMetricValue: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: "700",
    },
    recordMetricLabel: {
      color: theme.colors.textSubtle,
      fontSize: 11,
      fontWeight: "600",
      letterSpacing: 0.5,
      textTransform: "uppercase",
    },
    splitGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "flex-start",
      justifyContent: "center",
      gap: PLACE_DASHBOARD_GRID_GAP,
    },
    mapPanel: {
      width: dashboardCardSize,
      height: dashboardCardSize,
      borderRadius: scaleDashboard(16),
      overflow: "hidden",
      backgroundColor: theme.colors.surface,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
      elevation: 2,
    },
    mapCanvas: {
      position: "relative",
      width: "100%",
      height: "100%",
      overflow: "hidden",
      borderRadius: scaleDashboard(16),
      backgroundColor: theme.colors.surfaceMuted,
    },
    amapInteractiveMap: {
      width: "100%",
      height: "100%",
      borderRadius: scaleDashboard(16),
    },
    osmMapContainer: {
      width: "100%",
      height: "100%",
      position: "relative",
      zIndex: 1,
      borderRadius: scaleDashboard(16),
    },
    osmMapImage: {
      width: "100%",
      height: "100%",
    },
    osmMapMarker: {
      position: "absolute",
      top: "50%",
      left: "50%",
      marginLeft: scaleDashboard(-12),
      marginTop: scaleDashboard(-24),
    },
    osmMapAttribution: {
      position: "absolute",
      bottom: scaleDashboard(4),
      right: scaleDashboard(4),
      backgroundColor: theme.colors.glassStrong,
      paddingHorizontal: scaleDashboard(4),
      paddingVertical: scaleDashboard(1),
      borderRadius: scaleDashboard(4),
    },
    osmMapAttributionText: {
      fontSize: scaleDashboard(8),
      color: theme.colors.textMuted,
    },
    mapPlaceholder: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: scaleDashboard(6),
      backgroundColor: theme.colors.surfaceSubtle,
      borderRadius: scaleDashboard(16),
    },
    mapPlaceholderText: {
      color: theme.colors.textMuted,
      fontSize: scaleDashboard(12),
      fontWeight: "600",
    },
    mapOverlayAction: {
      position: "absolute",
      top: scaleDashboard(10),
      right: scaleDashboard(10),
      zIndex: 2,
      flexDirection: "row",
      alignItems: "center",
    },
    mapOverlayButton: {
      alignItems: "center",
      justifyContent: "center",
      width: scaleDashboard(32),
      height: scaleDashboard(32),
      borderRadius: scaleDashboard(16),
      backgroundColor: theme.colors.glassStrong,
    },
    mapOverlayButtonPressed: {
      backgroundColor: theme.colors.primarySoft,
    },
    mapCaption: {
      color: theme.colors.textMuted,
      fontSize: scaleDashboard(12),
      fontWeight: "500",
      lineHeight: scaleDashboard(17),
    },
    weatherPanel: {
      width: dashboardCardSize,
      height: dashboardCardSize,
      overflow: "hidden",
      justifyContent: "space-between",
      gap: scaleWeather(3),
      padding: scaleWeather(10),
      borderRadius: scaleDashboard(16),
      borderWidth: 1,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: scaleWeather(5),
      elevation: 2,
    },
    weatherTopRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: scaleWeather(6),
    },
    weatherEyebrowRow: {
      flex: 1,
      minWidth: 0,
      flexDirection: "row",
      alignItems: "center",
      gap: scaleWeather(5),
    },
    weatherAccentDot: {
      width: scaleWeather(6),
      height: scaleWeather(6),
      borderRadius: scaleWeather(3),
    },
    weatherEyebrow: {
      flexShrink: 1,
      fontSize: scaleWeather(11),
      fontWeight: "700",
      letterSpacing: scaleWeather(0.1),
    },
    weatherSourceCompact: {
      maxWidth: "52%",
      flexDirection: "row",
      alignItems: "center",
      gap: scaleWeather(3),
      paddingHorizontal: scaleWeather(6),
      paddingVertical: scaleWeather(3),
      borderRadius: 999,
    },
    weatherSourceCompactText: {
      flexShrink: 1,
      fontSize: scaleWeather(9),
      fontWeight: "700",
    },
    weatherHeroRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: scaleWeather(8),
    },
    weatherHeroCopy: {
      flex: 1,
      minWidth: 0,
      gap: scaleWeather(2),
    },
    weatherTemperature: {
      fontSize: scaleWeather(27),
      fontWeight: "800",
      lineHeight: scaleWeather(30),
      letterSpacing: scaleWeather(-0.8),
    },
    weatherMetaLine: {
      fontSize: scaleWeather(10.5),
      fontWeight: "600",
    },
    weatherIconBubble: {
      width: scaleWeather(46),
      height: scaleWeather(46),
      flexShrink: 0,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: scaleWeather(16),
    },
    weatherMetricsRow: {
      flexDirection: "row",
      gap: scaleWeather(5),
    },
    weatherMetric: {
      flex: 1,
      minWidth: 0,
      minHeight: scaleWeather(47),
      justifyContent: "center",
      gap: scaleWeather(3),
      paddingHorizontal: scaleWeather(7),
      paddingVertical: scaleWeather(5),
      borderRadius: scaleWeather(11),
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.03,
      shadowRadius: 1,
      elevation: 1,
    },
    weatherMetricLabelRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: scaleWeather(3),
    },
    weatherMetricLabel: {
      flexShrink: 1,
      fontSize: scaleWeather(10),
      fontWeight: "600",
    },
    weatherMetricValue: {
      fontSize: scaleWeather(16),
      fontWeight: "800",
    },
    weatherFooter: {
      minHeight: scaleWeather(18),
      flexDirection: "row",
      alignItems: "flex-end",
    },
    weatherRiskRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: scaleWeather(5),
    },
    weatherRiskBadge: {
      maxWidth: scaleWeather(88),
      flexDirection: "row",
      alignItems: "center",
      gap: scaleWeather(4),
      paddingHorizontal: scaleWeather(7),
      paddingVertical: scaleWeather(4),
      borderRadius: 999,
    },
    weatherRiskDot: {
      width: scaleWeather(5),
      height: scaleWeather(5),
      flexShrink: 0,
      borderRadius: scaleWeather(3),
    },
    weatherRiskBadgeText: {
      flexShrink: 1,
      fontSize: scaleWeather(10),
      fontWeight: "600",
    },
    weatherEmptyState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: scaleWeather(6),
      paddingHorizontal: scaleWeather(8),
    },
    weatherEmptyTitle: {
      fontSize: scaleWeather(16),
      fontWeight: "800",
      textAlign: "center",
    },
    weatherEmptyDescription: {
      fontSize: scaleWeather(11),
      fontWeight: "600",
      lineHeight: scaleWeather(16),
      textAlign: "center",
    },
    summaryPanelTouch: {
      width: dashboardCardSize,
      height: dashboardCardSize,
      borderRadius: scaleDashboard(16),
    },
    summaryPanelPressed: {
      opacity: 0.88,
      transform: [{ scale: 0.99 }],
    },
    summaryPanel: {
      flex: 1,
      overflow: "hidden",
      justifyContent: "space-between",
      gap: scaleDashboard(8),
      padding: scaleDashboard(14),
      borderRadius: scaleDashboard(16),
      borderWidth: 0,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: theme.mode === "dark" ? 0.16 : 0.08,
      shadowRadius: scaleDashboard(5),
      elevation: 2,
    },
    summaryPanelHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: scaleDashboard(8),
    },
    summaryEyebrowRow: {
      flex: 1,
      minWidth: 0,
      flexDirection: "row",
      alignItems: "center",
      gap: scaleDashboard(5),
    },
    summaryAccentDot: {
      width: scaleDashboard(6),
      height: scaleDashboard(6),
      flexShrink: 0,
      borderRadius: scaleDashboard(3),
    },
    summaryEyebrow: {
      flexShrink: 1,
      fontSize: scaleDashboard(12),
      fontWeight: "800",
    },
    summaryBadge: {
      maxWidth: "48%",
      paddingHorizontal: scaleDashboard(8),
      paddingVertical: scaleDashboard(4),
      borderRadius: 999,
    },
    summaryBadgeText: {
      fontSize: scaleDashboard(11),
      fontWeight: "800",
    },
    summaryHeroRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: scaleDashboard(10),
    },
    summaryHeroCopy: {
      flex: 1,
      minWidth: 0,
      gap: scaleDashboard(3),
    },
    summaryTitle: {
      fontSize: scaleDashboard(21),
      fontWeight: "800",
      lineHeight: scaleDashboard(25),
    },
    summaryTitleLarge: {
      fontSize: scaleDashboard(24),
      fontWeight: "900",
      lineHeight: scaleDashboard(28),
    },
    summarySubtitle: {
      fontSize: scaleDashboard(12),
      fontWeight: "700",
      lineHeight: scaleDashboard(16),
    },
    summaryIconBubble: {
      width: scaleDashboard(48),
      height: scaleDashboard(48),
      flexShrink: 0,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: scaleDashboard(17),
    },
    summaryInsightList: {
      minHeight: scaleDashboard(42),
      gap: scaleDashboard(5),
    },
    summaryInsightRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: scaleDashboard(5),
    },
    summaryInsightText: {
      flex: 1,
      fontSize: scaleDashboard(12),
      fontWeight: "700",
      lineHeight: scaleDashboard(17),
    },
    summaryPlaceholder: {
      fontSize: scaleDashboard(12),
      fontWeight: "700",
      lineHeight: scaleDashboard(17),
    },
    summaryLatestBox: {
      minHeight: scaleDashboard(46),
      justifyContent: "center",
      gap: scaleDashboard(4),
      paddingTop: scaleDashboard(8),
      borderTopWidth: 1,
      borderTopColor: theme.colors.glassBorder,
    },
    summaryLatestAmount: {
      fontSize: scaleDashboard(13),
      fontWeight: "800",
    },
    summaryTagRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: scaleDashboard(5),
      marginTop: "auto",
    },
    summaryTag: {
      maxWidth: scaleDashboard(86),
      paddingHorizontal: scaleDashboard(8),
      paddingVertical: scaleDashboard(4),
      borderRadius: 999,
    },
    summaryTagText: {
      fontSize: scaleDashboard(10.5),
      fontWeight: "800",
    },
    reviewMoodHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    reviewMoodCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    reviewBadge: {
      overflow: "hidden",
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
      backgroundColor: theme.colors.surfaceMuted,
      color: theme.colors.slate,
      fontSize: 11,
      fontWeight: "600",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.03,
      shadowRadius: 1,
      elevation: 1,
    },
    insightGrid: {
      flexDirection: "row",
      gap: 10,
    },
    insightBox: {
      flex: 1,
      gap: 8,
      padding: 14,
      borderRadius: 14,
      borderWidth: 1,
    },
    insightBoxGood: {
      backgroundColor: theme.colors.successSoft,
      borderColor: theme.colors.success,
      shadowColor: theme.colors.success,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 2,
      elevation: 1,
    },
    insightBoxCaution: {
      backgroundColor: theme.colors.warningSoft,
      borderColor: theme.colors.warning,
      shadowColor: theme.colors.warning,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 2,
      elevation: 1,
    },
    insightTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    insightTitle: {
      color: theme.colors.text,
      fontSize: 13,
      fontWeight: "700",
    },
    insightText: {
      color: theme.colors.slate,
      fontSize: 13,
      fontWeight: "500",
      lineHeight: 19,
    },
    tagRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    tagChip: {
      overflow: "hidden",
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 20,
      backgroundColor: theme.colors.surfaceMuted,
      color: theme.colors.slate,
      fontSize: 12,
      fontWeight: "600",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.03,
      shadowRadius: 1,
      elevation: 1,
    },
    placeholderText: {
      color: theme.colors.textSubtle,
      fontSize: 13,
      fontWeight: "500",
      lineHeight: 19,
    },
    noteBlock: {
      gap: 6,
      paddingTop: 4,
    },
    noteHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    noteUnsavedText: {
      color: theme.colors.primary,
      fontSize: 11,
      fontWeight: "600",
    },
    noteText: {
      color: theme.colors.slate,
      fontSize: 13,
      lineHeight: 20,
    },
    costInlineHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    costCollapsedAction: {
      alignItems: "flex-end",
      gap: 2,
      paddingTop: 4,
    },
    costCollapsedActionLine: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    costCollapsedActionText: {
      color: theme.colors.primary,
      fontSize: 12,
      fontWeight: "600",
    },
    costInlineTitle: {
      flex: 1,
      minWidth: 0,
      gap: 4,
    },
    costInlineRow: {
      minHeight: 40,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingTop: 8,
    },
    costPrefix: {
      color: theme.colors.success,
      fontSize: 16,
      fontWeight: "700",
    },
    costInlineInput: {
      minHeight: 44,
      flex: 1,
      minWidth: 0,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.borderStrong,
      backgroundColor: theme.colors.surface,
      color: theme.colors.text,
      fontSize: 14,
      fontWeight: "500",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 2,
      elevation: 1,
    },
    costInlineSaveButton: {
      minHeight: 44,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 16,
      borderRadius: 12,
      backgroundColor: theme.colors.primary,
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      elevation: 3,
    },
    costInlineSaveButtonDisabled: {
      backgroundColor: theme.colors.surfaceSubtle,
      shadowOpacity: 0,
      elevation: 0,
    },
    costInlineSaveButtonText: {
      color: theme.colors.surface,
      fontSize: 12,
      fontWeight: "600",
    },
    costInlineCancelButton: {
      minHeight: 44,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 14,
      borderRadius: 12,
      backgroundColor: theme.colors.surfaceMuted,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 2,
      elevation: 1,
    },
    costInlineCancelButtonText: {
      color: theme.colors.slate,
      fontSize: 12,
      fontWeight: "600",
    },
    costErrorText: {
      color: theme.colors.danger,
      fontSize: 11,
      fontWeight: "600",
      lineHeight: 16,
    },
    noteInput: {
      minHeight: 80,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.borderStrong,
      backgroundColor: theme.colors.surface,
      color: theme.colors.text,
      fontSize: 14,
      lineHeight: 20,
    },
    noteActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
    },
    noteSaveButton: {
      minHeight: 38,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingHorizontal: 16,
      borderRadius: 12,
      backgroundColor: theme.colors.primary,
    },
    noteSaveButtonPressed: {
      backgroundColor: theme.colors.primaryPressed,
    },
    noteSaveButtonDisabled: {
      backgroundColor: theme.colors.surfaceSubtle,
    },
    noteSaveButtonText: {
      color: theme.colors.surface,
      fontSize: 13,
      fontWeight: "700",
    },
    noteSaveButtonTextDisabled: {
      color: theme.colors.textSubtle,
    },
    emptyBlock: {
      alignItems: "center",
      gap: 6,
      paddingVertical: 12,
    },
    inlineError: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 12,
      backgroundColor: theme.colors.dangerSoft,
      borderWidth: 1,
      borderColor: theme.colors.dangerBorder,
      shadowColor: theme.colors.danger,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 2,
      elevation: 1,
    },
    inlineErrorText: {
      color: theme.colors.danger,
      fontSize: 12,
      fontWeight: "600",
    },
    externalLinksCard: {
      gap: 0,
      padding: 6,
    },
    linkRow: {
      width: "100%",
      minHeight: 52,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderRadius: 10,
    },
    linkRowDivider: {
      borderBottomColor: theme.colors.border,
      borderBottomWidth: 1,
    },
    linkIcon: {
      alignItems: "center",
      justifyContent: "center",
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: theme.colors.primarySoft,
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 2,
      elevation: 1,
    },
    linkCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    primaryButton: {
      alignSelf: "flex-start",
      paddingHorizontal: 18,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: theme.colors.primary,
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      elevation: 3,
    },
    primaryButtonText: {
      color: theme.colors.surface,
      fontSize: 13,
      fontWeight: "600",
    },
    bottomActionBar: {
      position: "absolute",
      bottom: 14,
      alignSelf: "center",
      width: `${PLACE_BOTTOM_ACTION_BAR_WIDTH_RATIO * 100}%`,
      maxWidth: PLACE_BOTTOM_ACTION_BAR_MAX_WIDTH,
      flexDirection: "row",
      alignItems: "center",
      gap: 0,
      paddingHorizontal: 8,
      height: 52,
      borderRadius: 26,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.colors.glassBorder,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 16,
      elevation: 8,
    },
    bottomActionButton: {
      flex: 1,
      height: 40,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
      borderRadius: 20,
      backgroundColor: "transparent",
      paddingHorizontal: 8,
    },
    bottomActionButtonPressed: {
      backgroundColor: theme.colors.surfacePressed,
    },
    bottomActionButtonActive: {
      backgroundColor: theme.colors.primarySoft,
    },
    bottomActionText: {
      color: theme.colors.text,
      fontSize: 11,
      fontWeight: "600",
    },
    bottomActionTextActive: {
      color: theme.colors.primary,
    },
    moreMenuBackdrop: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 10,
      backgroundColor: "transparent",
    },
    moreMenu: {
      position: "absolute",
      bottom: 78,
      zIndex: 12,
      width: PLACE_MORE_MENU_WIDTH,
      overflow: "hidden",
      gap: 7,
      padding: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 16,
      backgroundColor: theme.colors.surface,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.14,
      shadowRadius: 16,
      elevation: 12,
    },
    moreMenuTitle: {
      paddingHorizontal: 8,
      paddingTop: 3,
      color: theme.colors.textMuted,
      fontSize: 11,
      fontWeight: "600",
    },
    moreMenuItem: {
      minHeight: 58,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 10,
      paddingVertical: 9,
      borderRadius: 13,
    },
    moreMenuItemPressed: {
      backgroundColor: theme.colors.surfacePressed,
    },
    moreMenuItemDisabled: {
      opacity: 0.65,
    },
    moreMenuItemIcon: {
      width: 34,
      height: 34,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 11,
      backgroundColor: theme.colors.primarySoft,
    },
    moreMenuItemCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    moreMenuItemTitle: {
      color: theme.colors.text,
      fontSize: 13,
      fontWeight: "700",
    },
    moreMenuItemHint: {
      color: theme.colors.textMuted,
      fontSize: 10,
      lineHeight: 14,
    },
    moreMenuEmptyText: {
      paddingHorizontal: 10,
      paddingVertical: 12,
      color: theme.colors.textMuted,
      fontSize: 12,
    },
    imageViewerContainer: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.95)",
    },
    imageViewerClose: {
      position: "absolute",
      top: 50,
      right: 20,
      zIndex: 10,
      width: 44,
      height: 44,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 22,
      backgroundColor: "rgba(255, 255, 255, 0.15)",
    },
    imageViewerCounter: {
      position: "absolute",
      top: 56,
      left: 0,
      right: 0,
      zIndex: 10,
      textAlign: "center",
      color: "#FFFFFF",
      fontSize: 15,
      fontWeight: "600",
    },
    imageViewerScroll: {
      flex: 1,
    },
    imageViewerSlide: {
      width: SCREEN_WIDTH,
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    imageViewerImage: {
      width: SCREEN_WIDTH,
      height: SCREEN_WIDTH * 0.75,
    },
    imageViewerSource: {
      position: "absolute",
      bottom: 40,
      color: "rgba(255, 255, 255, 0.7)",
      fontSize: 12,
      fontWeight: "500",
    },
  });
}
