import { Platform, StyleSheet } from "react-native";

import type { AppTheme } from "@/shared/theme/theme";

export const avatarCropSize = 280;
export const avatarCropPreviewSize = 68;

export function createProfileScreenStyles(theme: AppTheme) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
    },

    content: {
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 144,
      gap: 14,
    },
    profileHeader: {
      alignItems: "center",
      gap: 12,
      paddingTop: 8,
      paddingBottom: 18,
    },
    profileMenuButton: {
      position: "absolute",
      top: 4,
      right: 0,
      zIndex: 2,
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 20,
      borderWidth: 0,
      shadowColor: theme.colors.text,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    profileAvatarWrap: {
      width: 96,
      height: 96,
      alignItems: "center",
      justifyContent: "center",
    },
    profileAvatar: {
      width: 88,
      height: 88,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 44,
      overflow: "hidden",
      backgroundColor: theme.colors.linkSoft,
      borderColor: theme.colors.surface,
      borderWidth: 0,
      shadowColor: theme.colors.text,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    profileAvatarText: {
      color: theme.colors.link,
      fontSize: 24,
      fontWeight: "900",
      letterSpacing: 0,
    },
    profileAvatarImage: {
      width: 88,
      height: 88,
      borderRadius: 44,
    },
    avatarEditButton: {
      position: "absolute",
      right: 0,
      bottom: 2,
      width: 30,
      height: 30,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 15,
      shadowColor: theme.colors.text,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    profileNameRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    profileName: {
      color: theme.colors.text,
      fontSize: 30,
      fontWeight: "900",
      letterSpacing: 0,
    },
    profileSubtitle: {
      maxWidth: 320,
      color: theme.colors.textMuted,
      fontSize: 14,
      fontWeight: "600",
      lineHeight: 20,
      textAlign: "center",
    },
    profileStats: {
      alignSelf: "center",
      width: "100%",
      flexDirection: "row",
      alignItems: "stretch",
      justifyContent: "space-between",
      gap: 24,
      maxWidth: 460,
      marginTop: 4,
      paddingTop: 8,
    },
    profileStatItem: {
      flex: 1,
      minWidth: 0,
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 8,
      paddingVertical: 8,
    },
    profileStatLabel: {
      color: theme.colors.textMuted,
      fontSize: 12,
      fontWeight: "900",
      letterSpacing: 1,
      lineHeight: 17,
      textAlign: "center",
    },
    profileStatValue: {
      color: theme.colors.text,
      fontFamily: Platform.select({
        android: "serif",
        default: "serif",
        ios: "Georgia",
        web: 'Georgia, "Times New Roman", serif',
      }),
      fontSize: 29,
      fontVariant: ["tabular-nums"],
      fontWeight: "700",
      letterSpacing: -0.8,
      lineHeight: 34,
      textAlign: "center",
    },
    profileGlassCard: {
      borderWidth: 0,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },

    accountCard: {
      gap: 14,
      padding: 20,
      borderRadius: 20,
      borderWidth: 1,
    },
    loginLightAccountCard: {
      backgroundColor: theme.colors.glass,
      borderColor: theme.colors.glassBorder,
    },
    accountHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    avatar: {
      width: 58,
      height: 58,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 29,
    },
    avatarText: {
      fontSize: 20,
      fontWeight: "800",
    },
    accountCopy: {
      flex: 1,
      gap: 4,
    },
    accountName: {
      fontSize: 20,
      fontWeight: "800",
    },
    card: {
      gap: 14,
      padding: 16,
      borderRadius: 12,
      borderWidth: 1,
    },
    signedInStack: {
      gap: 16,
    },
    loginPanel: {
      gap: 14,
      paddingVertical: 0,
    },
    loginHero: {
      minHeight: 98,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 14,
      paddingTop: 0,
      paddingBottom: 4,
    },
    logoStage: {
      width: 118,
      height: 94,
      alignItems: "center",
      justifyContent: "center",
      overflow: "visible",
    },
    logoImage: {
      width: 112,
      height: 92,
      resizeMode: "contain",
    },
    loginBrandCopy: {
      alignItems: "flex-start",
      gap: 1,
    },
    loginBrand: {
      fontSize: 24,
      fontWeight: "900",
      letterSpacing: 0,
      lineHeight: 30,
    },
    loginTitle: {
      fontSize: 12,
      fontWeight: "500",
      lineHeight: 18,
      textAlign: "left",
    },
    emailForm: {
      gap: 12,
    },

    loginMethodTabs: {
      minHeight: 44,
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      padding: 4,
      borderRadius: 22,
      borderWidth: 1,
    },
    loginMethodTab: {
      flex: 1,
      minHeight: 36,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 18,
      borderWidth: 1,
      paddingHorizontal: 10,
    },
    loginMethodTabText: {
      fontSize: 13,
      fontWeight: "800",
    },
    loginMethodHint: {
      fontSize: 12,
      lineHeight: 18,
      paddingHorizontal: 2,
      textAlign: "center",
    },
    loginMethodForm: {
      gap: 12,
    },
    loginLinkPlaceholder: {
      height: 28,
    },
    loginLinkButton: {
      alignSelf: "center",
      height: 28,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 8,
      borderRadius: 14,
    },
    loginLinkButtonText: {
      fontSize: 13,
      fontWeight: "800",
    },
    phoneLogin: {
      gap: 8,
    },
    inputGroup: {
      gap: 6,
    },
    inputLabel: {
      fontSize: 12,
      fontWeight: "700",
    },
    input: {
      minHeight: 50,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 8,
      borderWidth: 1,
      fontSize: 15,
    },
    loginInputShell: {
      height: 54,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 14,
      borderRadius: 16,
      borderWidth: 1,
    },
    loginTextInput: {
      flex: 1,
      height: 48,
      paddingVertical: 10,
      fontSize: 15,
    },
    textArea: {
      minHeight: 82,
      textAlignVertical: "top",
    },
    scaleStepper: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    scaleButton: {
      width: 36,
      height: 36,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 18,
    },
    scaleTrackTouchArea: {
      flex: 1,
      height: 36,
      justifyContent: "center",
    },
    scaleTrack: {
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.colors.border,
    },
    scaleTrackFill: {
      height: "100%",
      borderRadius: 4,
    },
    scaleTrackThumb: {
      position: "absolute",
      top: -4,
      width: 16,
      height: 16,
      marginLeft: -8,
      borderRadius: 8,
      borderWidth: 3,
      borderColor: theme.colors.surface,
    },
    scaleValue: {
      minWidth: 42,
      fontSize: 12,
      fontWeight: "800",
      textAlign: "right",
    },
    codeRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      height: 54,
      paddingHorizontal: 14,
      paddingVertical: 4,
      borderRadius: 16,
      borderWidth: 1,
    },
    codeInlineInput: {
      flex: 1,
      height: 48,
      paddingVertical: 10,
      fontSize: 15,
    },
    codeTextButton: {
      minWidth: 72,
      minHeight: 36,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 10,
      borderRadius: 18,
    },
    codeTextButtonText: {
      fontSize: 14,
      fontWeight: "800",
    },

    primaryButton: {
      minHeight: 44,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingHorizontal: 14,
      borderRadius: 8,
    },
    primaryButtonText: {
      color: theme.colors.onPrimary,
      fontSize: 15,
      fontWeight: "800",
    },
    secondaryButton: {
      minHeight: 44,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 14,
      borderRadius: 8,
      borderWidth: 1,
    },
    secondaryButtonText: {
      fontSize: 15,
      fontWeight: "800",
    },
    loginButton: {
      minHeight: 56,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingHorizontal: 18,
      borderRadius: 28,
      shadowColor: theme.colors.text,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.18,
      shadowRadius: 18,
      elevation: 5,
    },
    loginButtonText: {
      color: theme.colors.onPrimary,
      fontSize: 16,
      fontWeight: "900",
    },
    agreementRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 8,
      paddingHorizontal: 4,
    },
    agreementCheck: {
      width: 18,
      height: 18,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 9,
      marginTop: 2,
    },
    agreementText: {
      flex: 1,
      fontSize: 13,
      lineHeight: 20,
    },
    socialLoginSection: {
      marginTop: 4,
      gap: 16,
    },
    socialLoginDividerRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    socialLoginDividerLine: {
      flex: 1,
      height: 1,
    },
    socialLoginDividerText: {
      fontSize: 12,
      fontWeight: "600",
    },
    socialLoginIcons: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 32,
    },
    socialLoginIconWrap: {
      alignItems: "center",
      gap: 6,
    },
    socialLoginIcon: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: "center",
      justifyContent: "center",
    },
    guestLoginIcon: {
      borderWidth: 1,
    },
    socialLoginLabel: {
      fontSize: 11,
      fontWeight: "600",
    },
    wechatButton: {
      minHeight: 44,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingHorizontal: 14,
      borderRadius: 8,
      borderWidth: 1,
    },
    wechatButtonText: {
      fontSize: 15,
      fontWeight: "800",
    },
    statusMessage: {
      fontSize: 12,
      lineHeight: 18,
    },
    quickActionCard: {
      alignSelf: "center",
      width: "100%",
      maxWidth: 620,
      flexDirection: "row",
      alignItems: "stretch",
      justifyContent: "space-between",
      gap: 4,
      paddingVertical: 8,
      borderRadius: theme.radius.lg,
    },
    quickActionItem: {
      flex: 1,
      minWidth: 0,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 8,
      borderRadius: theme.radius.md,
    },
    quickActionIcon: {
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    quickActionTitle: {
      fontWeight: "800",
      lineHeight: 18,
      textAlign: "center",
    },
    settingSectionCard: {
      overflow: "hidden",
      paddingVertical: 12,
      borderRadius: theme.radius.lg,
    },
    settingSectionTitle: {
      paddingHorizontal: 18,
      paddingBottom: 4,
      fontSize: 14,
      fontWeight: "800",
      lineHeight: 20,
    },
    settingListRow: {
      minHeight: 70,
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
      paddingHorizontal: 18,
      paddingVertical: 12,
    },
    settingIcon: {
      width: 38,
      height: 38,
      flexShrink: 0,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: theme.radius.sm,
    },
    segmentedControl: {
      flexDirection: "row",
      gap: 4,
      padding: 4,
      marginHorizontal: 18,
      marginBottom: 12,
      borderRadius: 10,
    },
    segmentedOption: {
      minHeight: 38,
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderRadius: 8,
      paddingHorizontal: 8,
    },
    segmentedOptionText: {
      fontSize: 13,
      fontWeight: "700",
    },
    settingDivider: {
      height: 1,
      marginLeft: 70,
      opacity: 0.72,
    },
    profileEditorOverlay: {
      flex: 1,
      alignItems: "center",
      justifyContent: "flex-end",
    },
    profileEditorSheet: {
      width: "100%",
      maxWidth: 560,
      maxHeight: "92%",
      overflow: "hidden",
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      borderWidth: 1,
      borderBottomWidth: 0,
      shadowColor: theme.colors.text,
      shadowOffset: { width: 0, height: -12 },
      shadowOpacity: 0.16,
      shadowRadius: 30,
      elevation: 12,
    },
    profileEditorHeader: {
      minHeight: 68,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 18,
      borderBottomWidth: 1,
    },
    profileEditorHeaderButton: {
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 20,
    },
    profileEditorTitle: {
      flex: 1,
      paddingHorizontal: 12,
      fontSize: 18,
      fontWeight: "900",
      textAlign: "center",
    },
    profileEditorSaveButton: {
      minWidth: 66,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 20,
      paddingHorizontal: 16,
    },
    profileEditorSaveText: {
      fontSize: 14,
      fontWeight: "900",
    },
    profileEditorContent: {
      gap: 20,
      paddingHorizontal: 20,
      paddingTop: 24,
      paddingBottom: 36,
    },
    profileEditorAvatarSection: {
      alignItems: "center",
      gap: 7,
    },
    profileEditorAvatarButton: {
      position: "relative",
      width: 112,
      height: 112,
      alignItems: "center",
      justifyContent: "center",
    },
    profileEditorAvatar: {
      width: 104,
      height: 104,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      borderRadius: 52,
      borderWidth: 0,
      shadowColor: theme.colors.text,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    profileEditorAvatarImage: {
      width: 104,
      height: 104,
      borderRadius: 52,
    },
    profileEditorAvatarText: {
      fontSize: 28,
      fontWeight: "900",
    },
    profileEditorCameraBadge: {
      position: "absolute",
      right: 2,
      bottom: 2,
      width: 36,
      height: 36,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 18,
      borderWidth: 0,
    },
    profileEditorTextAction: {
      minHeight: 24,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 12,
    },
    profileEditorTextActionLabel: {
      fontSize: 15,
      fontWeight: "900",
    },
    profileEditorRemoveLabel: {
      fontSize: 13,
      fontWeight: "700",
    },
    profileEditorFormCard: {
      overflow: "hidden",
      borderRadius: 20,
      borderWidth: 0,
    },
    profileEditorField: {
      gap: 7,
      paddingHorizontal: 18,
      paddingVertical: 15,
    },
    profileEditorFieldHeading: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    profileEditorFieldLabel: {
      fontSize: 12,
      fontWeight: "800",
      letterSpacing: 0.5,
    },
    profileEditorCounter: {
      fontSize: 11,
      fontWeight: "700",
    },
    profileEditorInput: {
      minHeight: 32,
      padding: 0,
      fontSize: 16,
      fontWeight: "700",
      lineHeight: 23,
    },
    profileEditorBioInput: {
      minHeight: 88,
      fontWeight: "500",
    },
    profileEditorDivider: {
      height: 1,
      marginLeft: 18,
    },
    profileEditorHint: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 9,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 14,
    },
    profileEditorHintText: {
      flex: 1,
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 18,
    },
    passwordPromptOverlay: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      padding: 22,
      backgroundColor: theme.colors.overlay,
    },
    passwordPromptCard: {
      width: "100%",
      maxWidth: 420,
      gap: 14,
      padding: 18,
      borderRadius: 16,
      borderWidth: 1,
      position: "relative",
      shadowColor: theme.colors.text,
      shadowOffset: { width: 0, height: 18 },
      shadowOpacity: 0.16,
      shadowRadius: 30,
      elevation: 8,
    },
    passwordPromptCloseButton: {
      position: "absolute",
      top: 14,
      right: 14,
      zIndex: 1,
      width: 34,
      height: 34,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 17,
    },
    passwordPromptIcon: {
      width: 52,
      height: 52,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 26,
      backgroundColor: theme.colors.primarySoft,
    },
    passwordPromptTitle: {
      fontSize: 21,
      fontWeight: "900",
      lineHeight: 28,
    },
    passwordPromptBody: {
      fontSize: 14,
      lineHeight: 21,
    },
    passwordPromptForm: {
      gap: 10,
    },
    passwordPromptActions: {
      flexDirection: "row",
      gap: 10,
    },
    passwordPromptAction: {
      flex: 1,
    },
    cropModalRoot: {
      flex: 1,
      backgroundColor: "#090B10",
    },
    cropModalHeader: {
      minHeight: 72,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 8,
    },
    cropHeaderButton: {
      minWidth: 70,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 20,
      paddingHorizontal: 14,
    },
    cropHeaderSecondaryButton: {
      backgroundColor: "rgba(255, 255, 255, 0.1)",
    },
    cropHeaderSecondaryButtonPressed: {
      backgroundColor: "rgba(255, 255, 255, 0.18)",
    },
    cropHeaderButtonText: {
      color: "#FFFFFF",
      fontSize: 15,
      fontWeight: "800",
    },
    cropConfirmText: {
      color: theme.colors.onPrimary,
      fontSize: 15,
      fontWeight: "900",
    },
    cropTitleGroup: {
      alignItems: "center",
      gap: 2,
    },
    cropTitle: {
      color: "#FFFFFF",
      fontSize: 18,
      fontWeight: "900",
    },
    cropTitleCaption: {
      color: "rgba(255, 255, 255, 0.62)",
      fontSize: 11,
      fontWeight: "600",
    },
    cropStage: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 20,
      paddingVertical: 18,
    },
    cropFrame: {
      width: avatarCropSize,
      height: avatarCropSize,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      borderRadius: avatarCropSize / 2,
      cursor: "pointer",
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: 0.36,
      shadowRadius: 28,
      elevation: 14,
      userSelect: "none",
    },
    cropImageLayer: {
      ...StyleSheet.absoluteFillObject,
      alignItems: "center",
      justifyContent: "center",
    },
    cropImage: {
      position: "absolute",
    },
    cropGrid: {
      ...StyleSheet.absoluteFillObject,
      overflow: "hidden",
      borderRadius: avatarCropSize / 2,
    },
    cropGridVertical: {
      position: "absolute",
      top: 0,
      bottom: 0,
      width: StyleSheet.hairlineWidth,
      backgroundColor: "rgba(255, 255, 255, 0.3)",
    },
    cropGridHorizontal: {
      position: "absolute",
      right: 0,
      left: 0,
      height: StyleSheet.hairlineWidth,
      backgroundColor: "rgba(255, 255, 255, 0.3)",
    },
    cropFrameOverlay: {
      position: "absolute",
      width: avatarCropSize,
      height: avatarCropSize,
      borderRadius: avatarCropSize / 2,
      borderWidth: 3,
      borderColor: "rgba(255, 255, 255, 0.86)",
    },
    cropControls: {
      gap: 16,
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 24,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
    },
    cropPreviewRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
    },
    cropPreviewFrame: {
      width: avatarCropPreviewSize,
      height: avatarCropPreviewSize,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      borderRadius: avatarCropPreviewSize / 2,
      borderWidth: 2,
      borderColor: theme.colors.border,
    },
    cropPreviewCopy: {
      flex: 1,
      gap: 3,
    },
    cropPreviewTitle: {
      fontSize: 15,
      fontWeight: "900",
    },
    cropHint: {
      fontSize: 13,
      fontWeight: "700",
      lineHeight: 18,
    },
    cropToolRow: {
      flexDirection: "row",
      gap: 10,
    },
    cropToolButton: {
      flex: 1,
      minHeight: 52,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 7,
      borderRadius: 16,
    },
    cropToolLabel: {
      fontSize: 13,
      fontWeight: "800",
    },

    settingCopy: {
      flex: 1,
      gap: 4,
      minWidth: 0,
    },
    itemTitle: {
      fontSize: 16,
      fontWeight: "700",
    },
    mutedText: {
      fontSize: 14,
      lineHeight: 20,
    },
  });
}
