create table if not exists admin.agent_runtime_config (
  singleton boolean primary key default true check (singleton),
  config_version bigint not null default 1 check (config_version > 0),
  enabled boolean not null default true,
  disabled_skill_ids text[] not null default '{}'::text[],
  minimum_app_version text not null default '2026.06.22-0448'
    check (minimum_app_version ~ '^[0-9]+([.-][0-9]+)*$'),
  protocol_version integer not null default 1 check (protocol_version > 0),
  allowed_model_profiles text[] not null default array['router', 'balanced']::text[]
    check (
      cardinality(allowed_model_profiles) > 0
      and allowed_model_profiles <@ array['router', 'balanced', 'quality']::text[]
    ),
  model_profiles jsonb not null default '{
    "router": "deepseek-v4-flash",
    "balanced": "deepseek-v4-flash"
  }'::jsonb
    check (jsonb_typeof(model_profiles) = 'object'),
  minute_limit integer not null default 6 check (minute_limit between 1 and 10000),
  daily_limit integer not null default 60 check (daily_limit between 1 and 10000),
  telemetry_enabled boolean not null default true,
  updated_by uuid references auth.users (id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into admin.agent_runtime_config (singleton)
values (true)
on conflict (singleton) do nothing;

drop trigger if exists set_agent_runtime_config_updated_at
  on admin.agent_runtime_config;
create trigger set_agent_runtime_config_updated_at
  before update on admin.agent_runtime_config
  for each row
  execute function admin.set_updated_at();

create table if not exists admin.agent_runtime_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  conversation_id text,
  turn_id text,
  attempt_id text,
  phase text not null check (
    phase in ('route_selector', 'waylog_qa', 'trip_draft', 'itinerary_edit')
  ),
  prompt_version text,
  app_version text,
  model_profile text,
  model text,
  provider text,
  status text not null check (status in ('succeeded', 'failed')),
  failure_kind text,
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  input_tokens integer check (input_tokens is null or input_tokens >= 0),
  output_tokens integer check (output_tokens is null or output_tokens >= 0),
  total_tokens integer check (total_tokens is null or total_tokens >= 0),
  tool_events jsonb not null default '[]'::jsonb
    check (jsonb_typeof(tool_events) = 'array'),
  operation_count integer check (operation_count is null or operation_count >= 0),
  escalated_from text,
  escalation_reason text,
  created_at timestamptz not null default now()
);

create index if not exists agent_runtime_events_user_created_idx
  on admin.agent_runtime_events (user_id, created_at desc);
create index if not exists agent_runtime_events_phase_created_idx
  on admin.agent_runtime_events (phase, created_at desc);
create index if not exists agent_runtime_events_failure_created_idx
  on admin.agent_runtime_events (failure_kind, created_at desc)
  where failure_kind is not null;

alter table admin.agent_runtime_config enable row level security;
alter table admin.agent_runtime_events enable row level security;

revoke all on table admin.agent_runtime_config from public;
revoke all on table admin.agent_runtime_events from public;
grant all on table admin.agent_runtime_config to service_role;
grant all on table admin.agent_runtime_events to service_role;
grant usage on sequence admin.agent_runtime_events_id_seq to service_role;

create or replace function public.get_agent_runtime_config()
returns jsonb
language sql
security definer
set search_path = admin, public
as $$
  select jsonb_build_object(
    'allowedModelProfiles', allowed_model_profiles,
    'configVersion', config_version,
    'dailyLimit', daily_limit,
    'disabledSkillIds', disabled_skill_ids,
    'enabled', enabled,
    'minimumAppVersion', minimum_app_version,
    'minuteLimit', minute_limit,
    'modelProfiles', model_profiles,
    'protocolVersion', protocol_version,
    'telemetryEnabled', telemetry_enabled
  )
  from admin.agent_runtime_config
  where singleton = true;
$$;

revoke all on function public.get_agent_runtime_config() from public;
grant execute on function public.get_agent_runtime_config() to service_role;

create or replace function public.record_agent_runtime_event(
  p_user_id uuid,
  p_conversation_id text,
  p_turn_id text,
  p_attempt_id text,
  p_phase text,
  p_prompt_version text,
  p_app_version text,
  p_model_profile text,
  p_model text,
  p_provider text,
  p_status text,
  p_failure_kind text,
  p_duration_ms integer,
  p_input_tokens integer,
  p_output_tokens integer,
  p_total_tokens integer,
  p_tool_events jsonb,
  p_operation_count integer,
  p_escalated_from text,
  p_escalation_reason text
)
returns void
language plpgsql
security definer
set search_path = admin, public
as $$
begin
  if p_phase not in ('route_selector', 'waylog_qa', 'trip_draft', 'itinerary_edit') then
    raise exception 'Unsupported Agent phase';
  end if;
  if p_status not in ('succeeded', 'failed') then
    raise exception 'Unsupported Agent telemetry status';
  end if;
  if jsonb_typeof(coalesce(p_tool_events, '[]'::jsonb)) <> 'array'
    or jsonb_array_length(coalesce(p_tool_events, '[]'::jsonb)) > 16 then
    raise exception 'Invalid Agent tool telemetry';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(coalesce(p_tool_events, '[]'::jsonb)) as event
    where jsonb_typeof(event) <> 'object'
      or event - array['name', 'status']::text[] <> '{}'::jsonb
      or not ((event ? 'name') and (event ? 'status'))
      or jsonb_typeof(event -> 'name') <> 'string'
      or jsonb_typeof(event -> 'status') <> 'string'
      or event ->> 'status' not in ('requested', 'completed', 'failed')
      or length(event ->> 'name') not between 1 and 200
  ) then
    raise exception 'Agent tool telemetry contains non-whitelisted fields';
  end if;

  insert into admin.agent_runtime_events (
    user_id,
    conversation_id,
    turn_id,
    attempt_id,
    phase,
    prompt_version,
    app_version,
    model_profile,
    model,
    provider,
    status,
    failure_kind,
    duration_ms,
    input_tokens,
    output_tokens,
    total_tokens,
    tool_events,
    operation_count,
    escalated_from,
    escalation_reason
  )
  values (
    p_user_id,
    left(p_conversation_id, 200),
    left(p_turn_id, 200),
    left(p_attempt_id, 200),
    p_phase,
    left(p_prompt_version, 200),
    left(p_app_version, 200),
    left(p_model_profile, 200),
    left(p_model, 200),
    left(p_provider, 200),
    p_status,
    left(p_failure_kind, 200),
    greatest(0, p_duration_ms),
    greatest(0, p_input_tokens),
    greatest(0, p_output_tokens),
    greatest(0, p_total_tokens),
    coalesce(p_tool_events, '[]'::jsonb),
    least(100, greatest(0, p_operation_count)),
    left(p_escalated_from, 200),
    left(p_escalation_reason, 200)
  );
end;
$$;

revoke all on function public.record_agent_runtime_event(
  uuid, text, text, text, text, text, text, text, text, text, text, text,
  integer, integer, integer, integer, jsonb, integer, text, text
) from public;
grant execute on function public.record_agent_runtime_event(
  uuid, text, text, text, text, text, text, text, text, text, text, text,
  integer, integer, integer, integer, jsonb, integer, text, text
) to service_role;

create or replace function public.get_agent_runtime_usage(
  p_daily_limit integer default 60
)
returns jsonb
language plpgsql
security definer
set search_path = admin, public
as $$
declare
  v_user_id uuid := auth.uid();
  v_window_start timestamptz := now() - interval '24 hours';
  v_daily_used integer := 0;
  v_reset_at timestamptz;
  v_model_calls integer := 0;
  v_tool_calls integer := 0;
  v_duration_ms bigint := 0;
  v_escalations integer := 0;
  v_model_profile text;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;
  if p_daily_limit <= 0 then
    raise exception 'Daily limit must be positive';
  end if;

  select count(*)::integer, min(called_at) + interval '24 hours'
  into v_daily_used, v_reset_at
  from public.agent_calls
  where user_id = v_user_id
    and called_at > v_window_start;

  select
    count(*) filter (where model is not null)::integer,
    coalesce(sum(jsonb_array_length(tool_events)), 0)::integer,
    coalesce(sum(duration_ms), 0),
    count(*) filter (where escalated_from is not null)::integer
  into v_model_calls, v_tool_calls, v_duration_ms, v_escalations
  from admin.agent_runtime_events
  where user_id = v_user_id
    and created_at > v_window_start;

  select model_profile
  into v_model_profile
  from admin.agent_runtime_events
  where user_id = v_user_id
    and created_at > v_window_start
    and model_profile is not null
  order by created_at desc
  limit 1;

  return jsonb_strip_nulls(jsonb_build_object(
    'dailyLimit', p_daily_limit,
    'dailyUsed', coalesce(v_daily_used, 0),
    'dailyRemaining', greatest(0, p_daily_limit - coalesce(v_daily_used, 0)),
    'resetAt', v_reset_at,
    'modelCalls', coalesce(v_model_calls, 0),
    'toolCalls', coalesce(v_tool_calls, 0),
    'durationMs', coalesce(v_duration_ms, 0),
    'escalations', coalesce(v_escalations, 0),
    'modelProfile', v_model_profile
  ));
end;
$$;

revoke all on function public.get_agent_runtime_usage(integer) from public;
grant execute on function public.get_agent_runtime_usage(integer) to authenticated;

create or replace function public.consume_agent_turn_quota(
  p_minute_limit integer default 6,
  p_daily_limit integer default 60
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_now timestamptz := now();
  v_minute_window_start timestamptz := v_now - interval '60 seconds';
  v_day_window_start timestamptz := v_now - interval '24 hours';
  v_minute_count integer := 0;
  v_day_count integer := 0;
  v_retry_event_at timestamptz;
  v_retry_after integer := 0;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;
  if p_minute_limit <= 0 or p_daily_limit <= 0 then
    raise exception 'Rate limits must be positive';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(v_user_id::text, 0));

  select count(*)::integer into v_minute_count
  from public.agent_calls
  where user_id = v_user_id and called_at > v_minute_window_start;

  if coalesce(v_minute_count, 0) >= p_minute_limit then
    select called_at into v_retry_event_at
    from public.agent_calls
    where user_id = v_user_id and called_at > v_minute_window_start
    order by called_at asc
    offset greatest(v_minute_count - p_minute_limit, 0)
    limit 1;

    v_retry_after := greatest(1, ceil(extract(epoch from (
      coalesce(v_retry_event_at, v_now) + interval '60 seconds' - v_now
    )))::integer);

    return jsonb_build_object(
      'allowed', false,
      'bucket', 'minute',
      'minuteLimit', p_minute_limit,
      'minuteRemaining', 0,
      'retryAfterSeconds', v_retry_after
    );
  end if;

  select count(*)::integer into v_day_count
  from public.agent_calls
  where user_id = v_user_id and called_at > v_day_window_start;

  if coalesce(v_day_count, 0) >= p_daily_limit then
    select called_at into v_retry_event_at
    from public.agent_calls
    where user_id = v_user_id and called_at > v_day_window_start
    order by called_at asc
    offset greatest(v_day_count - p_daily_limit, 0)
    limit 1;

    v_retry_after := greatest(1, ceil(extract(epoch from (
      coalesce(v_retry_event_at, v_now) + interval '24 hours' - v_now
    )))::integer);

    return jsonb_build_object(
      'allowed', false,
      'bucket', 'day',
      'dailyLimit', p_daily_limit,
      'dailyUsed', coalesce(v_day_count, 0),
      'dailyRemaining', 0,
      'retryAfterSeconds', v_retry_after
    );
  end if;

  insert into public.agent_calls (user_id, called_at) values (v_user_id, v_now);

  return jsonb_build_object(
    'allowed', true,
    'minuteLimit', p_minute_limit,
    'minuteRemaining', greatest(0, p_minute_limit - coalesce(v_minute_count, 0) - 1),
    'dailyLimit', p_daily_limit,
    'dailyUsed', coalesce(v_day_count, 0) + 1,
    'dailyRemaining', greatest(0, p_daily_limit - coalesce(v_day_count, 0) - 1)
  );
end;
$$;

revoke all on function public.consume_agent_turn_quota(integer, integer) from public;
grant execute on function public.consume_agent_turn_quota(integer, integer) to authenticated;

do $migration$
begin
  if exists (select 1 from cron.job where jobname = 'cleanup-agent-runtime-events') then
    perform cron.unschedule('cleanup-agent-runtime-events');
  end if;
  perform cron.schedule(
    'cleanup-agent-runtime-events',
    '15 3 * * *',
    $cleanup$
      delete from admin.agent_runtime_events
      where created_at < now() - interval '30 days';
    $cleanup$
  );
end;
$migration$;

comment on table admin.agent_runtime_config is
  'Agent 版本化远程运行配置。singleton 行控制全局/Skill 开关、最低版本、协议、模型 profile 与 quota。';
comment on table admin.agent_runtime_events is
  'Agent 白名单遥测与 usage 汇总。禁止写入完整消息、Trip JSON、thinking、完整工具 payload、JWT、密钥或 signed URL。';
