create schema if not exists admin;

create table if not exists admin.admin_members (
  user_id uuid primary key references auth.users (id) on delete cascade,
  role text not null default 'readonly' check (role in ('owner', 'admin', 'developer', 'readonly')),
  display_name text,
  enabled boolean not null default true,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists admin.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users (id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  payload jsonb not null default '{}'::jsonb,
  ip inet,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_actor_created_at_idx
  on admin.admin_audit_logs (actor_user_id, created_at desc);

create index if not exists admin_audit_logs_target_idx
  on admin.admin_audit_logs (target_type, target_id);

create index if not exists admin_audit_logs_action_created_at_idx
  on admin.admin_audit_logs (action, created_at desc);

create or replace function admin.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_admin_members_updated_at on admin.admin_members;
create trigger set_admin_members_updated_at
  before update on admin.admin_members
  for each row
  execute function admin.set_updated_at();

alter table admin.admin_members enable row level security;
alter table admin.admin_audit_logs enable row level security;

revoke all on schema admin from public;
revoke all on all tables in schema admin from public;
revoke all on all functions in schema admin from public;

grant usage on schema admin to service_role;
grant all on all tables in schema admin to service_role;
grant all on all sequences in schema admin to service_role;
grant all on all functions in schema admin to service_role;

create or replace function public.get_current_admin_member()
returns table (
  user_id uuid,
  role text,
  display_name text,
  enabled boolean,
  note text
)
language sql
security definer
set search_path = admin, public
as $$
  select
    admin_members.user_id,
    admin_members.role,
    admin_members.display_name,
    admin_members.enabled,
    admin_members.note
  from admin.admin_members
  where admin_members.user_id = auth.uid()
    and admin_members.enabled = true
  limit 1;
$$;

create or replace function public.is_current_user_admin()
returns boolean
language sql
security definer
set search_path = admin, public
as $$
  select exists (
    select 1
    from admin.admin_members
    where admin_members.user_id = auth.uid()
      and admin_members.enabled = true
  );
$$;

create or replace function public.record_admin_audit_log(
  p_action text,
  p_target_type text default null,
  p_target_id text default null,
  p_payload jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = admin, public
as $$
declare
  v_audit_log_id bigint;
begin
  if not public.is_current_user_admin() then
    raise exception 'Admin permission required' using errcode = '42501';
  end if;

  insert into admin.admin_audit_logs (
    actor_user_id,
    action,
    target_type,
    target_id,
    payload
  )
  values (
    auth.uid(),
    p_action,
    p_target_type,
    p_target_id,
    coalesce(p_payload, '{}'::jsonb)
  )
  returning id into v_audit_log_id;

  return v_audit_log_id;
end;
$$;

revoke all on function public.get_current_admin_member() from public;
revoke all on function public.is_current_user_admin() from public;
revoke all on function public.record_admin_audit_log(text, text, text, jsonb) from public;

grant execute on function public.get_current_admin_member() to authenticated;
grant execute on function public.is_current_user_admin() to authenticated;
grant execute on function public.record_admin_audit_log(text, text, text, jsonb) to authenticated;

comment on schema admin is 'WayLog 后台管理系统私有 schema。';
comment on table admin.admin_members is '后台管理员成员表。Supabase Auth 负责登录，本表负责后台权限。';
comment on table admin.admin_audit_logs is '后台管理员操作审计日志。';
