create table if not exists public.agent_turn_quota_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists idx_agent_turn_quota_events_user_created_at
  on public.agent_turn_quota_events (user_id, created_at desc);

create index if not exists idx_agent_turn_quota_events_created_at
  on public.agent_turn_quota_events (created_at);

alter table public.agent_turn_quota_events enable row level security;

revoke all on table public.agent_turn_quota_events from public;
revoke all on table public.agent_turn_quota_events from anon;
revoke all on table public.agent_turn_quota_events from authenticated;

-- 旧版日桶没有单次请求时间，只能按窗口起点到最后更新时间做近似回填，避免迁移后 24 小时配额被直接清空。
insert into public.agent_turn_quota_events (user_id, created_at)
select
  rate_limits.user_id,
  rate_limits.window_start
    + (
      least(rate_limits.updated_at, now()) - rate_limits.window_start
    ) * ((series.request_number - 0.5)::double precision / rate_limits.request_count)
from public.agent_turn_rate_limits as rate_limits
cross join lateral generate_series(1, rate_limits.request_count) as series(request_number)
where rate_limits.bucket = 'day'
  and rate_limits.request_count > 0
  and rate_limits.updated_at > now() - interval '24 hours'
  and not exists (
    select 1
    from public.agent_turn_quota_events
  );

create extension if not exists pg_cron;

create or replace function public.consume_agent_turn_quota(
  p_minute_limit integer default 6,
  p_daily_limit integer default 60
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_now timestamptz := now();
  v_minute_start timestamptz := date_trunc('minute', v_now);
  v_previous_minute_start timestamptz := date_trunc('minute', v_now) - interval '1 minute';
  v_day_window_start timestamptz := v_now - interval '24 hours';
  v_minute_elapsed_seconds double precision := extract(epoch from (v_now - date_trunc('minute', v_now)));
  v_minute_elapsed_ratio double precision := extract(epoch from (v_now - date_trunc('minute', v_now))) / 60.0;
  v_minute_count integer := 0;
  v_previous_minute_count integer := 0;
  v_day_count integer := 0;
  v_minute_effective_count double precision := 0;
  v_minute_effective_after_count double precision := 0;
  v_daily_retry_event_at timestamptz;
  v_retry_after integer := 0;
  v_retry_after_seconds double precision := 0;
  v_retry_threshold double precision := 0;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  if p_minute_limit <= 0 or p_daily_limit <= 0 then
    raise exception 'Rate limits must be positive';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(v_user_id::text, 0));

  select
    coalesce(max(request_count) filter (where window_start = v_minute_start), 0),
    coalesce(max(request_count) filter (where window_start = v_previous_minute_start), 0)
  into v_minute_count, v_previous_minute_count
  from public.agent_turn_rate_limits
  where user_id = v_user_id
    and bucket = 'minute'
    and window_start in (v_minute_start, v_previous_minute_start);

  v_minute_effective_count :=
    (v_previous_minute_count * (1.0 - v_minute_elapsed_ratio)) + v_minute_count;

  if v_minute_effective_count + 1.0 > p_minute_limit then
    if v_minute_count + 1 <= p_minute_limit and v_previous_minute_count > 0 then
      v_retry_threshold := p_minute_limit - v_minute_count - 1;
      v_retry_after_seconds :=
        greatest(1.0, (60.0 * (1.0 - (v_retry_threshold / v_previous_minute_count))) - v_minute_elapsed_seconds);
    else
      v_retry_threshold := p_minute_limit - 1;
      if v_minute_count > 0 then
        v_retry_after_seconds :=
          (60.0 - v_minute_elapsed_seconds)
          + greatest(0.0, 60.0 * (1.0 - (v_retry_threshold / v_minute_count)));
      else
        v_retry_after_seconds := 60.0 - v_minute_elapsed_seconds;
      end if;
    end if;

    v_retry_after := greatest(1, ceil(v_retry_after_seconds)::integer);

    return jsonb_build_object(
      'allowed', false,
      'bucket', 'minute',
      'limit', p_minute_limit,
      'remaining', 0,
      'retryAfterSeconds', v_retry_after
    );
  end if;

  select count(*)::integer
  into v_day_count
  from public.agent_turn_quota_events
  where user_id = v_user_id
    and created_at > v_day_window_start;

  if coalesce(v_day_count, 0) >= p_daily_limit then
    select created_at
    into v_daily_retry_event_at
    from public.agent_turn_quota_events
    where user_id = v_user_id
      and created_at > v_day_window_start
    order by created_at asc
    offset greatest(v_day_count - p_daily_limit, 0)
    limit 1;

    v_retry_after := greatest(
      1,
      ceil(extract(epoch from (coalesce(v_daily_retry_event_at, v_now) + interval '24 hours' - v_now)))::integer
    );

    return jsonb_build_object(
      'allowed', false,
      'bucket', 'day',
      'limit', p_daily_limit,
      'remaining', 0,
      'retryAfterSeconds', v_retry_after
    );
  end if;

  insert into public.agent_turn_rate_limits (user_id, bucket, window_start, request_count, updated_at)
  values (v_user_id, 'minute', v_minute_start, 1, v_now)
  on conflict (user_id, bucket, window_start) do update
    set request_count = public.agent_turn_rate_limits.request_count + 1,
        updated_at = excluded.updated_at
  returning request_count into v_minute_count;

  insert into public.agent_turn_quota_events (user_id, created_at)
  values (v_user_id, v_now);

  v_minute_effective_after_count :=
    (v_previous_minute_count * (1.0 - v_minute_elapsed_ratio)) + v_minute_count;

  return jsonb_build_object(
    'allowed', true,
    'minuteLimit', p_minute_limit,
    'minuteRemaining', greatest(0, floor(p_minute_limit - v_minute_effective_after_count)::integer),
    'dailyLimit', p_daily_limit,
    'dailyRemaining', greatest(0, p_daily_limit - coalesce(v_day_count, 0) - 1)
  );
end;
$$;

revoke all on function public.consume_agent_turn_quota(integer, integer) from public;
grant execute on function public.consume_agent_turn_quota(integer, integer) to authenticated;

do $migration$
begin
  if exists (
    select 1
    from cron.job
    where jobname = 'cleanup-agent-rate-limits'
  ) then
    perform cron.unschedule('cleanup-agent-rate-limits');
  end if;

  perform cron.schedule(
    'cleanup-agent-rate-limits',
    '0 * * * *',
    $cleanup$
      delete from public.agent_turn_rate_limits
      where updated_at < now() - interval '3 days';

      delete from public.agent_turn_quota_events
      where created_at < now() - interval '3 days';
    $cleanup$
  );
end;
$migration$;
