create table if not exists admin.service_provider_configs (
  id uuid primary key default gen_random_uuid(),
  service_type text not null check (service_type in ('llm', 'map', 'poi', 'notification', 'monitoring')),
  provider_key text not null,
  display_name text not null,
  base_url text,
  default_model text,
  enabled boolean not null default false,
  config jsonb not null default '{}'::jsonb,
  secret_ref text,
  masked_secret text,
  secret_fingerprint text,
  secret_updated_at timestamptz,
  last_test_status text not null default 'untested' check (last_test_status in ('untested', 'success', 'failed')),
  last_test_message text,
  last_tested_at timestamptz,
  created_by uuid references auth.users (id) on delete set null,
  updated_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (service_type, provider_key)
);

create table if not exists admin.service_provider_secrets (
  id uuid primary key default gen_random_uuid(),
  config_id uuid not null unique references admin.service_provider_configs (id) on delete cascade,
  encrypted_secret text not null,
  encryption_version integer not null default 1,
  created_by uuid references auth.users (id) on delete set null,
  updated_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists admin.service_provider_versions (
  id bigint generated by default as identity primary key,
  config_id uuid not null references admin.service_provider_configs (id) on delete cascade,
  version_no integer not null,
  snapshot jsonb not null,
  change_reason text,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  unique (config_id, version_no)
);

create table if not exists admin.service_provider_test_runs (
  id bigint generated by default as identity primary key,
  config_id uuid not null references admin.service_provider_configs (id) on delete cascade,
  status text not null check (status in ('success', 'failed')),
  message text,
  checked_payload jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists service_provider_configs_type_updated_idx
  on admin.service_provider_configs (service_type, updated_at desc);

create index if not exists service_provider_configs_enabled_idx
  on admin.service_provider_configs (enabled, updated_at desc);

create index if not exists service_provider_configs_secret_fingerprint_idx
  on admin.service_provider_configs (secret_fingerprint)
  where secret_fingerprint is not null;

create index if not exists service_provider_versions_config_created_idx
  on admin.service_provider_versions (config_id, created_at desc);

create index if not exists service_provider_test_runs_config_created_idx
  on admin.service_provider_test_runs (config_id, created_at desc);

drop trigger if exists set_service_provider_configs_updated_at on admin.service_provider_configs;
create trigger set_service_provider_configs_updated_at
  before update on admin.service_provider_configs
  for each row
  execute function admin.set_updated_at();

drop trigger if exists set_service_provider_secrets_updated_at on admin.service_provider_secrets;
create trigger set_service_provider_secrets_updated_at
  before update on admin.service_provider_secrets
  for each row
  execute function admin.set_updated_at();

alter table admin.service_provider_configs enable row level security;
alter table admin.service_provider_secrets enable row level security;
alter table admin.service_provider_versions enable row level security;
alter table admin.service_provider_test_runs enable row level security;

revoke all on table admin.service_provider_configs from public;
revoke all on table admin.service_provider_secrets from public;
revoke all on table admin.service_provider_versions from public;
revoke all on table admin.service_provider_test_runs from public;

grant all on table admin.service_provider_configs to service_role;
grant all on table admin.service_provider_secrets to service_role;
grant all on table admin.service_provider_versions to service_role;
grant all on table admin.service_provider_test_runs to service_role;

grant usage on sequence admin.service_provider_versions_id_seq to service_role;
grant usage on sequence admin.service_provider_test_runs_id_seq to service_role;

comment on table admin.service_provider_configs is '后台服务配置中心。只保存非敏感配置、secret 引用、脱敏值和测试状态。';
comment on table admin.service_provider_secrets is '后台服务配置密钥密文表。仅服务端 service_role 可访问，前端不得读取。';
comment on table admin.service_provider_versions is '服务配置版本快照，用于追踪变更和后续回滚。';
comment on table admin.service_provider_test_runs is '服务配置连接测试记录。测试在后台服务端执行。';
comment on column admin.service_provider_configs.secret_ref is '密钥引用。MVP 指向 admin.service_provider_secrets 记录，后续可迁移到 Supabase Vault。';
comment on column admin.service_provider_configs.masked_secret is '仅用于后台展示的脱敏密钥，例如 ****abcd。';
comment on column admin.service_provider_configs.secret_fingerprint is '密钥 fingerprint，用于识别轮换，不能还原明文。';
