create table if not exists public.agent_calls (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  called_at timestamptz not null default now()
);

create index if not exists idx_agent_calls_user_called_at
  on public.agent_calls (user_id, called_at desc);

create index if not exists idx_agent_calls_called_at
  on public.agent_calls (called_at);

alter table public.agent_calls enable row level security;

revoke all on table public.agent_calls from public;
revoke all on table public.agent_calls from anon;
revoke all on table public.agent_calls from authenticated;

comment on table public.agent_calls is 'Agent 调用流水。每条记录代表一次通过限流并实际进入 agent-turn 的调用，用于分钟级和 24 小时额度统计。';
comment on column public.agent_calls.user_id is '发起 Agent 调用的用户。';
comment on column public.agent_calls.called_at is 'Agent 调用通过限流检查的时间。';

insert into public.agent_calls (user_id, called_at)
select quota_events.user_id, quota_events.created_at
from public.agent_turn_quota_events as quota_events
where not exists (
  select 1
  from public.agent_calls
);

create or replace function public.consume_agent_turn_quota(
  p_minute_limit integer default 6,
  p_daily_limit integer default 60
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_now timestamptz := now();
  v_minute_window_start timestamptz := v_now - interval '60 seconds';
  v_day_window_start timestamptz := v_now - interval '24 hours';
  v_minute_count integer := 0;
  v_day_count integer := 0;
  v_retry_event_at timestamptz;
  v_retry_after integer := 0;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  if p_minute_limit <= 0 or p_daily_limit <= 0 then
    raise exception 'Rate limits must be positive';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(v_user_id::text, 0));

  select count(*)::integer
  into v_minute_count
  from public.agent_calls
  where user_id = v_user_id
    and called_at > v_minute_window_start;

  if coalesce(v_minute_count, 0) >= p_minute_limit then
    select called_at
    into v_retry_event_at
    from public.agent_calls
    where user_id = v_user_id
      and called_at > v_minute_window_start
    order by called_at asc
    offset greatest(v_minute_count - p_minute_limit, 0)
    limit 1;

    v_retry_after := greatest(
      1,
      ceil(extract(epoch from (coalesce(v_retry_event_at, v_now) + interval '60 seconds' - v_now)))::integer
    );

    return jsonb_build_object(
      'allowed', false,
      'bucket', 'minute',
      'limit', p_minute_limit,
      'remaining', 0,
      'retryAfterSeconds', v_retry_after
    );
  end if;

  select count(*)::integer
  into v_day_count
  from public.agent_calls
  where user_id = v_user_id
    and called_at > v_day_window_start;

  if coalesce(v_day_count, 0) >= p_daily_limit then
    select called_at
    into v_retry_event_at
    from public.agent_calls
    where user_id = v_user_id
      and called_at > v_day_window_start
    order by called_at asc
    offset greatest(v_day_count - p_daily_limit, 0)
    limit 1;

    v_retry_after := greatest(
      1,
      ceil(extract(epoch from (coalesce(v_retry_event_at, v_now) + interval '24 hours' - v_now)))::integer
    );

    return jsonb_build_object(
      'allowed', false,
      'bucket', 'day',
      'limit', p_daily_limit,
      'remaining', 0,
      'retryAfterSeconds', v_retry_after
    );
  end if;

  insert into public.agent_calls (user_id, called_at)
  values (v_user_id, v_now);

  return jsonb_build_object(
    'allowed', true,
    'minuteLimit', p_minute_limit,
    'minuteRemaining', greatest(0, p_minute_limit - coalesce(v_minute_count, 0) - 1),
    'dailyLimit', p_daily_limit,
    'dailyRemaining', greatest(0, p_daily_limit - coalesce(v_day_count, 0) - 1)
  );
end;
$$;

revoke all on function public.consume_agent_turn_quota(integer, integer) from public;
grant execute on function public.consume_agent_turn_quota(integer, integer) to authenticated;

create extension if not exists pg_cron;

do $migration$
begin
  if exists (
    select 1
    from cron.job
    where jobname = 'cleanup-agent-rate-limits'
  ) then
    perform cron.unschedule('cleanup-agent-rate-limits');
  end if;

  if exists (
    select 1
    from cron.job
    where jobname = 'cleanup-agent-calls'
  ) then
    perform cron.unschedule('cleanup-agent-calls');
  end if;

  perform cron.schedule(
    'cleanup-agent-calls',
    '0 * * * *',
    $cleanup$
      delete from public.agent_calls
      where called_at < now() - interval '3 days';
    $cleanup$
  );
end;
$migration$;

drop table if exists public.agent_turn_rate_limits;
drop table if exists public.agent_turn_quota_events;
